### ISSUE TITLE
Add SAPI support

### ISSUE THREAD

**Issue by mrx23dot** [mediatechlab/tts-wrapper#4]
To have a complete picture we could add SAPI for windows:

https://github.com/DeepHorizons/tts

**Comment by mrx23dot** [comment]
The project above works great (even with SSML), 
also with the IVONA voices SAPI is very competitive, considering the rate limits of online services. 

So something like a wrapper could work, 
pip install TTS-Wrapper[sapi]
even if it just installs `pip install git+https://github.com/DeepHorizons/tts` as dependency.

(I also noticed the head doesn't work anymore with python 3.6, yaml config makes install fail)

**Comment by gbottari** [comment]
Hey @mrx23dot, are you still interested in this integration with SAPI?

I've made some improvements recently and even added an offline engine for Linux called PicoTTS. I think it would be easier to integrate with SAPI.

**Comment by gbottari** [comment]
Hey @mrx23dot. I've created a basic client for SAPI on [this](https://github.com/mediatechlab/tts-wrapper/tree/feature/sapi) branch. Could you test it on windows?

Oh, and I found another lib called [pyttsx3](https://github.com/nateshmbhat/pyttsx3) that appears to be more interesting than DeepHorizon's as it also supports SAPI, eSpeak and Mac OS' NSS.

**Comment by gbottari** [comment]
That's great @mrx23dot ! Thanks a lot!

I'll check IVONA later. Thanks for the tip!
