### ISSUE TITLE
Class variables should be prefixed with single underscore

### ISSUE THREAD

**Issue by gbottari** [mediatechlab/tts-wrapper#7]
### Description

According to [PEP8](https://peps.python.org/pep-0008/) we should use a single underscore in front of fields that are not part of the public API of a class.

This [article](https://medium.com/python-features/naming-conventions-with-underscores-in-python-791251ac7097) does a good job of explaining why we should use this convention.

This is present in most classes, like `PollyTTS`:

```python
class PollyTTS(AbstractTTS):
    def __init__(
        self,
        client: PollyClient,
        voice: Optional[str] = None,
    ) -> None:
        self.client = client  # should be changed to self._client
        self.voice = voice or "Joanna"   # should be changed to self._voice
```

**Comment by panoramix360** [comment]
@gbottari I think this issue could be closed after the merge of PR #13 :D
